openapi: 3.0.2
info:
  title: Neutralino.app
  version: 1.5.0
  description: '`Neutralino.app` namespace contains methods related to the current application instance.'
x-ref: |
  https://github.com/neutralinojs/neutralinojs.github.io/blob/main/docs/api/app.md
  https://github.com/neutralinojs/neutralinojs/blob/main/api/app/app.cpp
  https://github.com/neutralinojs/neutralino.js/blob/main/src/api/app.ts
paths:
  /__nativeMethod_app.exit:
    post:
      summary: exit
      operationId: Neutralino.app.exit
      tags:
        - App
      requestBody:
        $ref: '#/components/requestBodies/ExitRequest'
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
      description: |-
        Terminates the running application.

        ```js
        await Neutralino.app.exit();
        ```

        ```js
        await Neutralino.app.exit(130);
        ```
  /__nativeMethod_app.getConfig:
    get:
      summary: getConfig
      operationId: Neutralino.app.getConfig
      tags:
        - App
      responses:
        '200':
          $ref: '#/components/responses/GetConfigResponse'
      description: |-
        Returns the current application configuration as a JSON object.

        ```js
        Neutralino.app.getConfig ()
        ```
  /__nativeMethod_app.keepAlive:
    get:
      summary: keepAlive
      operationId: Neutralino.app.keepAlive
      tags:
        - App
      responses:
        '200':
          $ref: '#/components/responses/KeepAliveResponse'
      description: |-
        The keepAlive method is responsible for saving the Neutralinojs server instance from the automatic termination.
        This method is called automatically from the client library for the browser mode.

        ```js
        Neutralino.app.keepAlive();
        ```
          
  /__nativeMethod_app.killProcess:
    get:
      summary: killProcess
      operationId: Neutralino.app.killProcess
      tags:
        - App
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
      description: |-
        Kills the application process.
        If the application becomes unresponsive, you can use this to terminate the process instantly.
        However, we recommend you to use the `exit()` method to close your application properly.

        ```js
        await Neutralino.app.killProcess();
        ```
components:
  requestBodies:
    ExitRequest:
      content:
        application/json:
          schema:
            title: ExitQuery
            type: object
            properties:
              exitCode:
                type: integer
                description: An integer value for the process's exit code. The default value is always `0` (success).
  responses:
    AlwaysSuccessResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
                description: Always true
            required:
              - success
    GetConfigResponse:
      description: Application configuration
      content:
        application/json:
          schema:
            $ref: ../models/neutralino.config.schema.yaml
    KeepAliveResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
