openapi: 3.0.2
info:
  title: Neutralino.app
  version: 1.5.0
  description: '`Neutralino.debug` namespace contains application debugging utilities.'

x-ref: |
  https://github.com/neutralinojs/neutralinojs.github.io/blob/main/docs/api/computer.md
  https://github.com/neutralinojs/neutralinojs/blob/main/api/computer/computer.cpp
  https://github.com/neutralinojs/neutralino.js/blob/main/src/api/computer.ts
  
paths:

  /__nativeMethod_computer.getMemoryInfo:
    get:
      summary: computer.getMemoryInfo
      operationId: Neutralino.computer.getMemoryInfo
      tags: [Computer]
      responses:
        200:
          $ref: '#/components/responses/GetMemoryInfoResponse'
      description: |-
        Provides physical memory details (in megabytes).

        ```js
        let ramInfo = await Neutralino.computer.getRamUsage();
        console.log(`Your ram size: ${Math.round(ramInfo.total / 1000000)}GB`);
        ```

components:
  
  responses:

    GetMemoryInfoResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: string
              returnValue:
                $ref: '#/components/schemas/GetMemoryInfoResult'
            required:
              - "success"
              - "returnValue"

  schemas:
    
    GetMemoryInfoResult:
      type: object
      properties:
        total:
          type: number
          description: Total physical memory.
        available:
          type: number
          description: Available physical memory.
      required:
        - "total"
        - "available"
