openapi: 3.0.2
info:
  title: Neutralino API
  version: 1.5.0

servers:
  - url: 'http://localhost:{NL_PORT}'
    description: Neutralino server
    variables:
      NL_PORT:
        description: Application port
        default: '65097'

security:
  - basicAuth: []

paths: {}

components:

  securitySchemes:
    basicAuth:
      type: apiKey
      in: header
      name: Authorization 

  requestBodies: {}
  responses: {}
  schemas: {}
