openapi: 3.0.2
info:
  title: Neutralino.window
  version: 1.5.0
  description: |-
    `Neutralino.window` namespace contains methods related to the current native window instance.
    This namespace's methods will work only for the [window](https://neutralino.js.org/docs/configuration/modes#window) mode.
servers:
  - url: http://localhost
x-ref: |
  https://github.com/neutralinojs/neutralinojs.github.io/blob/main/docs/api/window.md
  https://github.com/neutralinojs/neutralinojs/blob/main/api/window/window.cpp
  https://github.com/neutralinojs/neutralino.js/blob/main/src/api/window.ts
paths:
  /window.setTitle:
    post:
      summary: setTitle
      operationId: Neutrlino.window.setTitle
      description: Sets the title of the native window.
      tags:
        - Window
      requestBody:
        $ref: '#/components/requestBodies/SetTitleRequest'
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
      x-codeSamples:
        - lang: JavaScript
          label: JS
          source: Neutralino.window.setTitle('New title')
  /window.setSize:
    post:
      summary: setSize
      operationId: neutralino_window_post_size
      description: |
        Resize the native window. \
        This feature is suitable to make custom window bars along with the [borderless mode](https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowborderless-boolean).

        This method always expects width and height couples. \
        For example, if you are sending `minWidth`, you should send `minHeight` too.
        ```js
        await Neutralino.window.setSize({
            width: 500,
            height: 200,
            maxWidth: 600,
            maxHeight: 400
        });

        await Neutralino.window.setSize({
            resizable: false
        });
        ```
      tags:
        - Window
      requestBody:
        $ref: '#/components/requestBodies/SetSizeRequest'
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.setIcon:
    post:
      summary: setIcon
      operationId: Neutralino.window.setIcon
      description: Sets an icon for the native window or Dock.
      tags:
        - Window
      requestBody:
        $ref: '#/components/requestBodies/SetIconRequest'
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
      x-doc: const icon = '/resources/icons/appIcon.png'; await Neutralino.window.setIcon(icon);
  /window.focus:
    get:
      summary: focus
      operationId: Neutralino.window.focus
      description: Focuses the native window.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.hide:
    get:
      summary: hide
      operationId: Neutralino.window.hide
      description: Hides the native window.
      tags:
        - Window
      responses:
        200:
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.isVisible:
    get:
      summary: isVisible
      operationId: Neutralino.window.isVisible
      description: Returns true if the native window is visible.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/IsVisibleResponse'
  /window.show:
    get:
      summary: show
      operationId: Neutralino.window.show
      description: Shows the native window.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.minimize:
    get:
      summary: minimize
      operationId: Neutralino.window.minimize
      description: Minimizes the native window.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.maximize:
    get:
      summary: maximize
      operationId: Neutralino.window.maximize
      description: Maximizes the native window.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.isMaximized:
    get:
      summary: isMaximized
      operationId: Neutralino.window.isMaximized
      description: Returns true if the native window is maximized.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/IsMaximizedResponse'
  /window.unmaximize:
    get:
      summary: unmaximize
      operationId: Neutralino.window.unmaximize
      description: Restores the native window.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.setFullScreen:
    get:
      summary: setFullScreen
      operationId: Neutralino.window.setFullScreen
      description: Enables the full screen mode.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.isFullScreen:
    get:
      summary: isFullScreen
      operationId: Neutralino.window.isFullScreen
      description: Returns true if the native window is in the full screen mode.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/IsFullScreenResponse'
  /window.exitFullScreen:
    get:
      summary: exitFullScreen
      operationId: Neutralino.window.exitFullScreen
      description: Exits from the full screen mode.
      tags:
        - Window
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
  /window.move:
    post:
      summary: move
      operationId: Neutralino.window.move
      description: |
        Moves the native window into given coordinates. \
        Neutralinojs's cross-platform coordinate system starts from top-left corner of the screen.
        In other words, `x=0,y=0` point refers to the top-left corner of the device's main screen.
      tags:
        - Window
      requestBody:
        $ref: '#/components/requestBodies/MoveRequest'
      responses:
        '200':
          $ref: '#/components/responses/AlwaysSuccessResponse'
components:
  securitySchemes:
    basicAuth:
      name: Authorization
      type: apiKey
      in: header
  requestBodies:
    SetTitleRequest:
      content:
        application/json:
          schema:
            title: SetTitleQuery
            properties:
              title:
                type: string
                description: Title of the window as a string.
            required:
              - title
          examples:
            default:
              value:
                title: New title
    SetSizeRequest:
      content:
        application/json:
          schema:
            title: SetSizeQuery
            type: object
            properties:
              width:
                type: number
                description: Window width in pixels.
              height:
                type: number
                description: Window height in pixels.
              minWidth:
                type: number
                description: Minimum width of the window in pixels.
              minHeight:
                type: number
                description: Minimum height of the window in pixels.
              maxWidth:
                type: number
                description: Maximum width of the window in pixels.
              maxHeight:
                type: number
                description: Maximum height of the window in pixels.
              resizable:
                type: number
                description: A boolean value to make the window resizable or fixed.
    SetIconRequest:
      content:
        application/json:
          schema:
            title: SetIconQuery
            type: object
            properties:
              icon:
                type: string
                description: Path of the icon. A `200x200` PNG image file works fine on all supported operating systems.
            required:
              - icon
    MoveRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              x:
                type: number
                description: A integer value for the horizontal position.
              'y':
                type: number
                description: A integer value for the vertical position.
            required:
              - x
              - 'y'
  responses:
    AlwaysSuccessResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
                description: Always true
            required:
              - success
    IsMaximizedResponse:
      description: OK
      content:
        application/json:
          schema:
            type: boolean
    IsFullScreenResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              returnValue:
                type: boolean
    IsVisibleResponse:
      description: OK
      content:
        application/json:
          schema:
            title: IsVisibleReturnValue
            type: boolean
